version: '3'
services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "RootAdmin123"
      MYSQL_ROOT_PASSWORD: "RootAdmin123"
      MYSQL_DATABASE: "updatepricesdb"
    ports:
      - "3306:3306"
    volumes:
      - ~/Projetos/Shopper/update-prices-api/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge